[workspace]
members = [
    "crates/lobster-source",
    "crates/lobster-diagnostics",
    "crates/lobster-ast",
    "crates/lobster-lexer",
    "crates/lobster-parser",
    "crates/lobster-cli",
    "crates/lobster-types",
    "crates/lobster-resolve",
    "crates/lobster-sema",
    "crates/lobster-hir",
    "crates/lobster-mir",
    "crates/lobster-interp",
    "crates/lobster-ssa",
    "crates/lobster-opt",
]
resolver = "2"

[workspace.lints.rust]
warnings = "deny"
